LINES = {
    "1": "red",
    "2": "red",
    "3": "red",
    "4": "green",
    "5": "green",
    "6": "green",
    "6+": "green",
    "7": "purple",
    "7+": "purple",
    "A": "blue",
    "C": "blue",
    "E": "blue",
    "B": "orange",
    "D": "orange",
    "F": "orange",
    "M": "orange",
    "G": "lime",
    "N": "yellow",
    "Q": "yellow",
    "R": "yellow",
    "W": "yellow",
    "L": "gray",
    "J": "brown",
    "Z": "brown",
}

PAGES = {
    "home.explorer": (0, "L"),
    "home.about": (5, "L"),
    "theory.making_1": (10, "6"),
    "theory.making_2": (11, "6+"),
    "photo.gallery": (20, "7"),
    "sound.proposal": (30, "B"),
    "sound.draft_1": (35, "D"),
    "sound.draft_2": (36, "F"),
    "sound.final": (37, "M"),
    "video.proposal": (40, "R"),
    "video.draft": (41, "N"),
    "video.final": (42, "Q"),
    "reading.pres": (50, "E"),
    "reading.written": (51, "C"),
    "reading.in_class_1": (52, "A"),
    "reading.in_class_2": (53, "A"),
    "final.draft_1": (60, "J", False),
    "sitemap.main": (70, "G"),
    "misc.ideas": (80, "J", False),
    "misc.survey_1": (81, "Z", False),
    "misc.survey_2": (82, "Z", False),
    "misc.photo_candidates": (83, "Z", False),
    "misc.sound_scratch": (84, "Z", False),
    "misc.video_scratch": (85, "Z", False),
}

SECTIONS = [
    ("home", "Home"),
    ("theory", "Theory Making"),
    ("photo", "Photography"),
    ("sound", "Sound Project"),
    ("video", "Video Project"),
    ("reading", "Reading Presentation"),
    ("sitemap", "Sitemap"),
    ("final", "Finals"),
    ("misc", "Miscellaneous"),
]