# Generated by Django 3.2.4 on 2021-06-25 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_name', models.CharField(max_length=512)),
                ('name', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_name', models.CharField(max_length=512)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Writing'), ('image', 'Photo'), ('audio', 'Audio'), ('video', 'Video')], max_length=32)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.location')),
                ('related', models.ManyToManyField(related_name='_web_multimedia_related_+', to='web.Multimedia')),
            ],
        ),
    ]
