# Generated by Django 3.2.4 on 2021-06-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
