# Generated by Django 3.2.4 on 2021-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210624_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_web_multimedia_related_+', to='web.Multimedia'),
        ),
    ]
