# Generated by Django 3.2.4 on 2021-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210626_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='qualified_name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='qualified_name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
