# Generated by Django 3.2.4 on 2021-06-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_multimedia_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
