# Generated by Django 3.2.4 on 2021-06-29 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_multimedia_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='radius',
            field=models.FloatField(default=0),
        ),
    ]
