# Generated by Django 3.2.4 on 2021-07-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210630_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='web.location'),
        ),
    ]
